/**
 * @license
 *-------------------------------------------------------------------------------------------
 * 
 *  See LICENSE.md in the package root for more information
 *-------------------------------------------------------------------------------------------
 */
"use client";
"use strict";Object.defineProperty(exports,Symbol.toStringTag,{value:"Module"});const k=require("react"),l=require("@progress/kno-react-common"),s=require("@progress/kno-svg-icons");function y(e){const t=Object.create(null,{[Symbol.toStringTag]:{value:"Module"}});if(e){for(const a in e)if(a!=="default"){const r=Object.getOwnPropertyDescriptor(e,a);Object.defineProperty(t,a,r.get?r:{enumerable:!0,get:()=>e[a]})}}return t.default=e,Object.freeze(t)}const o=y(k),C=e=>{const t=o.useRef(null),a=n=>{const c=t.current&&t.current.element;c&&e.onPress&&e.onPress(n.event,c)},r=n=>{const c=t.current&&t.current.element;c&&e.onDrag&&e.onDrag(n.event,c)},m=n=>{t.current&&t.current.element&&e.onRelease&&e.onRelease(n.event)},u=n=>{if(n.preventDefault(),e.onSortChange){const c=e.dir==="asc"?"desc":"asc";e.onSortChange(n,c)}},d=n=>{(n.keyCode===l.Keys.delete||n.keyCode===l.Keys.backspace)&&(n.preventDefault(),n.stopPropagation(),e.onRemove&&e.onRemove(n))},f=n=>{n.preventDefault(),n.stopPropagation(),e.onRemove&&e.onRemove(n)},g=n=>{const c={title:e.title,dir:e.dir,index:e.index};e.onContextMenu&&e.onContextMenu.call(void 0,n,{dataItem:{...c}})},{dir:i,title:b}=e;return o.createElement(l.Draggable,{onPress:a,onDrag:r,onRelease:m,ref:t},o.createElement("div",{className:"k-chip",onClick:u,onContextMenu:g,onKeyDown:d,tabIndex:0,role:"button",style:{touchAction:"none"}},o.createElement("span",null,o.createElement(l.IconWrap,{name:"sort-"+i+"-small",icon:i==="asc"?s.sortAscSmallIcon:s.sortDescSmallIcon,size:"small"})),o.createElement("span",{className:"k-chip-content"},o.createElement("span",{className:"k-chip-label"},b)),o.createElement("span",{className:"k-chip-actions"},o.createElement("span",{className:"k-chip-action k-chip-remove-action",onClick:f},o.createElement(l.IconWrap,{name:"x-circle",icon:s.xCircleIcon,size:"small"})))))};exports.GroupingIndicator=C;
