/**
 * @license
 *-------------------------------------------------------------------------------------------
 * 
 *  See LICENSE.md in the package root for more information
 *-------------------------------------------------------------------------------------------
 */
"use strict";Object.defineProperty(exports,Symbol.toStringTag,{value:"Module"});const j=require("react"),B=require("../AIPromptContent.js"),z=require("../AIPromptFooter.js"),q=require("@progress/kno-react-buttons"),P=require("@progress/kno-react-inputs"),F=require("@progress/kno-svg-icons"),C=require("@progress/kno-react-common"),G=require("./AIPromptViewRender.js"),M=require("../AIPromptExpander.js"),D=require("../AIPromptContext.js"),_=require("../../chat/components/SuggestionsGroup.js"),H=require("./constants.js");function W(o){const c=Object.create(null,{[Symbol.toStringTag]:{value:"Module"}});if(o){for(const r in o)if(r!=="default"){const n=Object.getOwnPropertyDescriptor(o,r);Object.defineProperty(c,r,n.get?n:{enumerable:!0,get:()=>o[r]})}}return c.default=o,Object.freeze(c)}const e=W(j),N=o=>{const{promptInput:c=P.TextArea,generateButton:r=q.Button,enableSpeechToText:n=!1,promptValue:b,promptSuggestions:f}=o,[a,p]=e.useState(b||""),[u]=D.useAIPromptContext(),[R,x]=C.useCustomComponent(r),[E,S]=C.useCustomComponent(c),T=()=>{u.onPromptRequest&&u.onPromptRequest.call(null,a),p("")},m=e.useRef(null),w=t=>{p(t)};e.useEffect(()=>{var t,s;(s=(t=m.current)==null?void 0:t.element)!=null&&s.current&&requestAnimationFrame(()=>{var l,g;if((g=(l=m.current)==null?void 0:l.element)!=null&&g.current){const i=m.current.element.current;i.style.height="auto",i.style.height=`${i.scrollHeight}px`}})},[a]);const y=t=>{p(t.target.value)},k={title:"Generate",children:"Generate",svgIcon:F.sparklesIcon},V={placeholder:"Ask or generate content with AI ...",rows:2},A=Object.keys(x).length>0?x:k,v=Object.keys(S).length>0?S:V,I=t=>{const{isFinal:s,alternatives:l}=t;if(s&&l.length>0){const g=l[0].transcript,i=(()=>{const d=a,O=d&&!d.endsWith(" ")&&!d.endsWith(`
`);return d+(O?" ":"")+g})();p(i)}};let h;return n&&(typeof n=="object"?h={...n,onResult:n.onResult||I}:h={onResult:I}),e.createElement(G.AIPromptViewRender,{name:H.promptViewDefaults.name},e.createElement(B.AIPromptContent,{streaming:u.streaming,onCancel:u.onCancel},e.createElement(E,{ref:m,value:a,flow:"vertical",textareaStyle:{maxHeight:"110px"},autoSize:!0,suffix:n?e.createElement(e.Fragment,null,e.createElement(P.InputSeparator,{orientation:"horizontal"}),e.createElement(P.InputSuffix,{orientation:"horizontal"},e.createElement(q.SpeechToTextButton,{fillMode:"flat",...h}))):void 0,onChange:y,...v}),f&&f.length>0&&e.createElement(M.AIPromptExpander,{title:"Prompt Suggestions"},e.createElement(_.SuggestionGroup,{suggestionsView:u.suggestionsView,suggestions:f.map((t,s)=>({id:s,text:t,description:t})),onSuggestionClick:t=>{w(t.text)}}))),e.createElement(z.AIPromptFooter,null,e.createElement(R,{themeColor:"primary",fillMode:"solid",rounded:"full",size:"medium",onClick:T,disabled:!a.trim(),...A},A.children)))};exports.AIPromptView=N;
