/**
 * @license
 *-------------------------------------------------------------------------------------------
 * 
 *  See LICENSE.md in the package root for more information
 *-------------------------------------------------------------------------------------------
 */
"use client";
"use strict";Object.defineProperty(exports,Symbol.toStringTag,{value:"Module"});const v=require("react"),a=require("@progress/kno-react-common"),O=require("../constants/index.js"),S=require("../utils/GridContext.js");function G(e){const r=Object.create(null,{[Symbol.toStringTag]:{value:"Module"}});if(e){for(const n in e)if(n!=="default"){const t=Object.getOwnPropertyDescriptor(e,n);Object.defineProperty(r,n,t.get?t:{enumerable:!0,get:()=>e[n]})}}return r.default=e,Object.freeze(r)}const c=G(v),H=e=>{var w;const r=c.useContext(S.GridContext),{reorderRowDropTargetRef:n,reorderRowDragTargetRef:t,activeDragRowDataItemRef:R}=r,{rowType:i,isAltRow:b,isInEdit:f,isSelected:m,isHighlighted:y,isPinned:D}=e,d=a.useUnstyled(),h=d&&d.uGrid?d.uGrid:a.uGrid,x=a.classNames(h.tr({selected:m,highlighted:y,isHeader:i==="groupHeader",isFooter:i==="groupFooter",isMaster:i!=="groupHeader"&&i!=="groupFooter",isAltRow:b,isInEdit:f,isPinned:D})),l=c.useRef(null),I=o=>{if(e.isRowReorderable&&R.current){const k=o.originalEvent.target;n.current=k.closest(".k-table-row")}},C=()=>{t.current&&e.isRowReorderable&&(t.current.style.userSelect="")};a.useDroppable(l,{onDragOver:I,onDrop:C});const T={onClick:o=>r.rowClick(o,e.dataItem),onDoubleClick:o=>r.rowDblClick(o,e.dataItem)},u={ref:l,id:e.id,...T,className:x,style:{height:e.rowHeight?e.rowHeight+"px":"",visibility:e.isHidden?"hidden":"",userSelect:(w=t==null?void 0:t.current)==null?void 0:w.style.userSelect},role:"row","aria-rowindex":e.ariaRowIndex,"absolute-row-index":e.absoluteRowIndex,[O.GRID_ROW_INDEX_ATTRIBUTE]:e.rowType==="data"?e.dataIndex:void 0},g=e.rowType||"data",s=e.rows;if(s&&s[g]){const o=s[g];return c.createElement(o,{key:e.absoluteRowIndex,...e,trProps:u},e.children)}return c.createElement("tr",{key:e.absoluteRowIndex,...u},e.children)};exports.GridRow=H;
