/**
 * @license
 *-------------------------------------------------------------------------------------------
 * 
 *  See LICENSE.md in the package root for more information
 *-------------------------------------------------------------------------------------------
 */
"use client";
"use strict";Object.defineProperty(exports,Symbol.toStringTag,{value:"Module"});const e=require("./chat/components/ChatMessage.js"),r=require("./chat/components/Chat.js"),p=require("./chat/components/SuggestionsGroup.js"),a=require("./chat/components/templates/HeroCard.js"),t=require("./chat/utils/fieldMapping.js"),s=require("./ai-prompt/AIPrompt.js"),m=require("./ai-prompt/AIPromptHeader.js"),n=require("./ai-prompt/AIPromptFooter.js"),i=require("./ai-prompt/AIPromptContent.js"),u=require("./ai-prompt/views/AIPromptView.js"),P=require("./ai-prompt/views/AIPromptOutputView.js"),A=require("./ai-prompt/views/AIPromptCommandsView.js"),c=require("./ai-prompt/views/AIPromptViewRender.js"),I=require("./inline-ai-prompt/InlineAIPrompt.js"),o=require("./ai-prompt/views/constants.js"),d=require("./prompt-box/PromptBox.js"),g=require("./prompt-box/PromptBoxActionButton.js"),B=require("./prompt-box/PromptBoxSpeechToTextButton.js"),q=require("./prompt-box/PromptBoxUploadButton.js");exports.ChatMessage=e.ChatMessage;exports.Chat=r.Chat;exports.SuggestionGroup=p.SuggestionGroup;exports.HeroCard=a.HeroCard;exports.DEFAULT_FIELD_MAPPING=t.DEFAULT_FIELD_MAPPING;exports.extractFieldMappingFromProps=t.extractFieldMappingFromProps;exports.isStandardMessageFormat=t.isStandardMessageFormat;exports.mapDataArrayToMessages=t.mapDataArrayToMessages;exports.mapDataToMessage=t.mapDataToMessage;exports.mapMessageToCustomFormat=t.mapMessageToCustomFormat;exports.AIPrompt=s.AIPrompt;exports.PromptHeader=m.PromptHeader;exports.AIPromptFooter=n.AIPromptFooter;exports.AIPromptContent=i.AIPromptContent;exports.AIPromptView=u.AIPromptView;exports.AIPromptOutputView=P.AIPromptOutputView;exports.AIPromptCommandsView=A.AIPromptCommandsView;exports.AIPromptViewRender=c.AIPromptViewRender;exports.InlineAIPrompt=I.InlineAIPrompt;exports.commandsViewDefaults=o.commandsViewDefaults;exports.outputViewDefaults=o.outputViewDefaults;exports.promptViewDefaults=o.promptViewDefaults;exports.PromptBox=d.PromptBox;exports.PromptBoxActionButton=g.PromptBoxActionButton;exports.PromptBoxSpeechToTextButton=B.PromptBoxSpeechToTextButton;exports.PromptBoxUploadButton=q.PromptBoxUploadButton;
