/**
 * @license
 *-------------------------------------------------------------------------------------------
 * 
 *  See LICENSE.md in the package root for more information
 *-------------------------------------------------------------------------------------------
 */
"use client";
"use strict";Object.defineProperty(exports,Symbol.toStringTag,{value:"Module"});const C=require("react"),s=require("@progress/kno-svg-icons"),n=require("../../messages/index.js"),u=require("@progress/kno-react-buttons"),v=require("@progress/kno-react-intl"),i=require("@progress/kno-react-layout"),k=require("../../columnMenu/GridColumnMenuItem.js"),h=require("../../columnMenu/GridColumnMenuItemGroup.js"),S=require("../../utils/GridContext.js"),b=require("../adaptiveContext/GridToolbarAdaptiveContext.js"),f=require("@progress/kno-react-common");function p(t){const a=Object.create(null,{[Symbol.toStringTag]:{value:"Module"}});if(t){for(const r in t)if(r!=="default"){const o=Object.getOwnPropertyDescriptor(t,r);Object.defineProperty(a,r,o.get?o:{enumerable:!0,get:()=>t[r]})}}return a.default=t,Object.freeze(a)}const e=p(C),E=t=>{const a=e.useContext(S.GridContext),{actionSheetRef:r}=e.useContext(b.GridToolbarAdaptiveContext),o=f.useAdaptiveModeContext(),l=v.useLocalization(),d={animation:!0,navigatable:!1,navigatableElements:[],expand:t.computedShow,animationStyles:o&&a.adaptiveColumnMenuRef<=o.small?{top:0,width:"100%",height:"100%"}:void 0,className:"k-adaptive-actionsheet",position:o&&a.adaptiveColumnMenuRef<=o.small?"fullscreen":void 0},m=l.toLanguageString(n.adaptiveToolbarSortTitle,n.messages[n.adaptiveToolbarSortTitle]);return e.createElement(i.ActionSheet,{...d,ref:r,style:{"--kno-actionsheet-view-current":1},onClose:t.onClose},e.createElement(i.ActionSheetView,null,e.createElement(i.ActionSheetHeader,null,e.createElement("div",{className:"k-actionsheet-titlebar-group"},e.createElement("div",{className:"k-actionsheet-title"},e.createElement("div",{className:"k-text-center"},m)),e.createElement("div",{className:"k-actionsheet-actions"},e.createElement(u.Button,{type:"button",svgIcon:s.checkIcon,themeColor:"primary",onClick:t.onClose,fillMode:"flat"})))),e.createElement(i.ActionSheetContent,null,e.createElement("div",{className:"k-column-menu k-column-menu-lg"},e.createElement(h.GridColumnMenuItemGroup,null,t.filtered.map(c=>e.createElement(k.GridColumnMenuItem,{key:c.id,title:t.renderTitle(c),onClick:g=>t.handleSorting(g,c)}))))),e.createElement(i.ActionSheetFooter,null,e.createElement("div",{className:"k-actions k-actions-stretched"},e.createElement(u.Button,{svgIcon:s.xIcon,onClick:t.onClear,size:"large",disabled:t.isDisabledButton},l.toLanguageString(n.sortClearButton,n.messages[n.sortClearButton])),e.createElement(u.Button,{svgIcon:s.checkIcon,themeColor:"primary",size:"large",onClick:t.onClose},l.toLanguageString(n.sortApplyButton,n.messages[n.sortApplyButton]))))))};exports.GridAdaptiveToolbarSort=E;
